### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group 

### ISSUE THREAD

**Issue by Daitargao** [dongzhang0725/PhyloSuite#38]
When I open my Phylosuite the program give one error as below. 

Traceback (most recent call last):
  File "codes\src\factory.py", line 2089, in slot
AttributeError: 'NoneType' object has no attribute 'group'

best regard

**Comment by dongzhang0725** [comment]
This problematic message is associated with a function that check if there is new version of PhyloSuite available, thus it will not affect the usage of PhyloSuite, so just click ok and use PhyloSuite normally. This problem is caused by your network, you can suppress it via unchecking "Check updates when opening PhyloSuite" chekbox in Settings --> Settings --> General menu.

**Comment by Daitargao** [comment]
thankyou Dong for this.
