### ISSUE TITLE
First install on macbook air m1 silicon

### ISSUE THREAD

**Issue by RisenL** [dongzhang0725/PhyloSuite#40]
Traceback (most recent call last):
  File "codes/src/factory.py", line 2089, in slot
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by dongzhang0725** [comment]
This problematic message is associated with a function that check if there is new version of PhyloSuite available, thus it will not affect the usage of PhyloSuite, so just click ok and use PhyloSuite normally. This problem is caused by network, you can suppress it via unchecking "Check updates when opening PhyloSuite" chekbox in Settings --> Settings --> General menu.
